# Generated by Django 3.1.6 on 2021-07-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact',
        ),
    ]
