# Generated by Django 3.1.6 on 2021-07-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='default_topic.jpg', upload_to='topic_images'),
        ),
    ]
