# Generated by Django 3.1.6 on 2021-07-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210713_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
    ]
