# Generated by Django 3.1.6 on 2021-07-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210714_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='blog.topic')),
            ],
        ),
    ]
