# Generated by Django 3.1.6 on 2021-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subtopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtopic',
            old_name='sub_name',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='sub_topic_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
