# Generated by Django 3.1.6 on 2021-07-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210714_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
