# Generated by Django 3.1.6 on 2021-07-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210718_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_image',
            field=models.ImageField(default=1, upload_to='topic_images'),
            preserve_default=False,
        ),
    ]
