# Generated by Django 3.2 on 2023-12-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='post_images/default.jpg', upload_to='post_images'),
        ),
    ]
