# Generated by Django 3.2 on 2023-12-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
