# Generated by Django 3.2 on 2023-12-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_post',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
